name: Update Crypto Prices

on:
  schedule:
    - cron: ""  # runs every hour
  workflow_dispatch:    # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Fetch latest prices and update file
        run: 

      - name: Commit and push changes
        run: |
        
        env:
          GH_TOKEN: 
          publish_dir: 
          publish_branch: gh-pages
          
